services:
  db:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

  blue:
    container_name: blue
    image: eedoy/gamagochi
    expose:
      - 8080
    ports:
      - 8081:8080
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}

  green:
    container_name: green
    image: eedoy/gamagochi
    expose:
      - 8080
    ports:
      - 8082:8080
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
