spring:
  application:
    name: SA_project

  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:mysql://gamagochi.c1ukcaym4bjl.ap-northeast-2.rds.amazonaws.com:3306/gamagochi
    username: admin4
    password: gachon4!#

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: simplekey123
